platform: linux
image_resource:
  type: registry-image
inputs:
  - name: eloq_metrics_src
  - name: txservice_src
  - name: redis_src
  - name: eloq_test_src
run:
  path: redis_src/concourse/scripts/main.bash
  args: ["((minio-endpoint))", "((minio-access-key))", "((minio-secret-key))"]
